import mongoose from "mongoose";
const schema = mongoose.Schema;

let Player = new mongoose.Schema({
  ALL_STAR_APPEARANCES: Number,
  AST: Number,
  BIRTHDATE: String,
  COUNTRY: String,
  DISPLAY_FIRST_LAST: String,
  DISPLAY_FI_LAST: String,
  DISPLAY_LAST_COMMA_FIRST: String,
  DLEAGUE_FLAG: String,
  DRAFT_NUMBER: String,
  DRAFT_ROUND: String,
  DRAFT_YEAR: String,
  FIRST_NAME: String,
  FROM_YEAR: String,
  GAMES_PLAYED_CURRENT_SEASON_FLAG: String,
  GAMES_PLAYED_FLAG: String,
  HEIGHT: Number,
  ID: String,
  JERSEY: String,
  LAST_AFFILIATION: String,
  LAST_NAME: String,
  NBA_FLAG: String,
  PIE: Number,
  PLAYERCODE: String,
  PLAYER_SLUG: String,
  POSITION: String,
  PTS: Number,
  REB: Number,
  ROSTERSTATUS: String,
  SCHOOL: String,
  SEASON_EXP: Number,
  TEAM_ABBREVIATION: String,
  TEAM_CITY: String,
  TEAM_CODE: String,
  TEAM_ID: String,
  TEAM_NAME: String,
  TO_YEAR: String,
  WEIGHT: Number,
});

export default mongoose.model("players", Player);
